### ISSUE TITLE
New image for TFX>22.0?

### ISSUE THREAD

**Issue by deep-diver** [valeriano-manassero/tfx-nvidia-gpu#12]
I really appreciate your work 

I ran into the same issue, but my TFX version is higher 0.27.0 and I think I need tf > 2.4 which requires cuda 11.x.

Can you help?

Thanks a lot!

**Comment by valeriano-manassero** [comment]
Hi @deep-diver ,
I tried to update the image with this PR https://github.com/valeriano-manassero/tfx-nvidia-gpu/pull/13 then tagging https://github.com/valeriano-manassero/tfx-nvidia-gpu/releases/tag/1.0.5 .

Since I don't have an active Kubeflow and I'm not using anymore TFX I'm not 100% sure it will work.

Pls take a try and let me know if the new image is working for you using tag `1.0.5` ( https://hub.docker.com/layers/valerianomanassero/tfx-nvidia-gpu/1.0.5/images/sha256-faed4697e1329ad7609a8e0520bdece61a0ed86ddfad31c5f1e42dc7dde66405?context=explore )

**Comment by deep-diver** [comment]
Thanks @valeriano-manassero !

I am trying to use custom docker image for Google Cloud AI Platform Training service.
Your previous version works perfect w/ TF <= 2.3!

However, the updated version doesnt seem to be working properly.
Thanks for your work putting your valuable time into this though!

I need to figure out what went wrong now myself...

<img width="1821" alt="Screen Shot 2021-02-16 at 2 42 40 PM" src="https://user-images.githubusercontent.com/26025527/108023124-42396e80-7065-11eb-86d1-bbcf201b2dce.png">

**Comment by valeriano-manassero** [comment]
Unfortunately it was a bit of "blind" upgrade since I don't have the cache to test the image atm. I'm pretty sure the libs are there (I checked the fs) so it looks like there is some path reference missing. It's possible I will have some time to test the docker image in some way in next weeks, in the meanwhile, pls keep me updated if you find something I can add to make it works. Thx!

**Comment by deep-diver** [comment]
Thanks

I suddenly realized that TF2.4 depends on CUDA version 11.0. 

And your updated version points to CUDA 11.2, so i am keep experimenting!

Let me know you shortly about what I have found!

**Comment by deep-diver** [comment]
Below is what I have found to be working with TF2.4 + CUDA11.0 + TFX>0.25.
`tfx-pipeline` is a docker image from [Chicago Taxi Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines), but not totally sure which TFX version it uses. (I just needed to make things running OK, so I will try to change it to `FROM tensorflow/tfx:0.27.0` later)

Anyways, with your scripts, I have learned how to include specific versions for CUDA and some related libraries to be installed!
I really appreciate it :) Thanks!

```Dockerfile
FROM gcr.io/gcp-ml-172005/tfx-pipeline

ENV CUDA_VERSION 11.0
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda=11.0 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450,driver<451"
ENV CUDNN_VERSION 8.0.5.39
ENV TF_FORCE_GPU_ALLOW_GROWTH true
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates apt-transport-https gnupg-curl && \
    NVIDIA_GPGKEY_SUM=d1be581509378368edeec8c1eb2958702feedf3bc3d17011adbf24efacce4ab5 && \
    NVIDIA_GPGKEY_FPR=ae09fe4bbd223a84b2ccfce3f60f4b3d7fa2af80 && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub && \
    apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +5 > cudasign.pub && \
    echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub && \
    echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update && apt-get install -y --no-install-recommends \
    cuda-cudart-11-0 \
    cuda-compat-11-0 \
    cuda-libraries-11-0 \
    libnpp-11-0 \
    cuda-nvtx-11-0 \
    libcublas-11-0 \
    libcusparse-11-0 \
    libcudnn8=$CUDNN_VERSION-1+cuda11.0 \
    cuda-cupti-11-0 \
    && ln -s cuda-11.0 /usr/local/cuda && \
    echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf \
    && echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf && \
    apt-get purge --auto-remove -y gnupg-curl && \
    apt-mark hold libcublas-11-2 && \
    apt-mark hold libcudnn8 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install tensorflow-gpu==2.4
ENTRYPOINT ["python3.7", "/tfx/tfx/scripts/run_executor.py"]
```

**Comment by valeriano-manassero** [comment]
Wow, awesome effort! If you want to publish the image feel free to send here the link to your repo and I will archive this one putting the link in README. wdyt?

**Comment by deep-diver** [comment]
I just made a repo trying to create various combinations of versions between TF, TFX, and CUDA!

Here is the [link](https://github.com/deep-diver/tfx-gpu-docker). This is my first try to write any dockerfile! so I am going to have to figure out how to publish though!

Thanks for the suggestion @valeriano-manassero :)

**Comment by valeriano-manassero** [comment]
I suggest to use GH Actions to publish the images, check https://github.com/valeriano-manassero/tfx-nvidia-gpu/blob/master/.github/workflows/dockerimage.yml so you can automate the image build and push to registry when tagging.

**Comment by deep-diver** [comment]
Thanks @valeriano-manassero ! I will absolutely check that out :D
